modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL = "https://github.com/PhantomWing/TheSilverAge/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/PhantomWing/TheSilverAge"
logoFile= "logo.png"
logoBlur=false
credits=""
authors="${mod_authors}"
description='''${mod_description}'''
## Catalogue mod compatibility
itemIcon = "thesilverage:silver_block"
configBackground = "minecraft:textures/block/bricks.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"